format = """
$directory$git_branch$git_status$nodejs$python$docker_context
$character"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
truncation_length = 3
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"

[nodejs]
symbol = " "

[python]
symbol = " "

[docker_context]
symbol = " "
